config/routes.rb
Rails.application.routes.draw do
  resources :departments

  devise_for :users
  get 'welcome/index'

  get 'welcome/about'

  get 'welcome/contact'

  resources :holidays

 root to: 'welcome#index'
 
end

app/models/department.rb
class Department < ActiveRecord::Base
end

app/models/holiday.rb
class Holiday < ActiveRecord::Base
end

app/models/holiday_search.rb
class HolidaySearch
  attr_reader :dateTo_from, :dateFrom_to
  
  def initialize(params)
    params ||= {}
    @dateTo_from = parsed_date(params[:dateTo_from], 7.days.ago.to_date.to_s)
    @dateFrom_to = parsed_date(params[:dateFrom_to], Date.today.to_s)
  end
  
  def scope
    Holiday.where('dateTo BETWEEN ? AND ?', @dateTo_from, @dateFrom_to)
  end
  
  private
  
  def parsed_date(date_string, default)
    Date.parse(date_string)
  rescue ArgumentError, TypeError
    default
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  #  :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  before_action :set_department, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @departments = Department.all
    respond_with(@departments)
  end

  def show
    respond_with(@department)
  end

  def new
    @department = Department.new
    respond_with(@department)
  end

  def edit
  end

  def create
    @department = Department.new(department_params)
    @department.save
    respond_with(@department)
  end

  def update
    @department.update(department_params)
    respond_with(@department)
  end

  def destroy
    @department.destroy
    respond_with(@department)
  end

  private
    def set_department
      @department = Department.find(params[:id])
    end

    def department_params
      params.require(:department).permit(:name, :position, :status)
    end
end

app/controllers/holidays_controller.rb
class HolidaysController < ApplicationController
  before_action :set_holiday, only: [:show, :edit, :update, :destroy]

  # GET /holidays
  # GET /holidays.json
  def index
    @search = HolidaySearch.new(params[:search])
    @holidays = @search.scope
  end


  # GET /holidays/1
  # GET /holidays/1.json
  def show
  end

  # GET /holidays/new
  def new
    @holiday = Holiday.new
  end

  # GET /holidays/1/edit
  def edit
  end

  # POST /holidays
  # POST /holidays.json
  def create
    @holiday = Holiday.new(holiday_params)

    respond_to do |format|
      if @holiday.save
        format.html { redirect_to @holiday, notice: 'Holiday was successfully requested.' }
        format.json { render :show, status: :created, location: @holiday }
      else
        format.html { render :new }
        format.json { render json: @holiday.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /holidays/1
  # PATCH/PUT /holidays/1.json
  def update
    respond_to do |format|
      if @holiday.update(holiday_params)
        format.html { redirect_to @holiday, notice: 'Holiday request was successfully updated.' }
        format.json { render :show, status: :ok, location: @holiday }
      else
        format.html { render :edit }
        format.json { render json: @holiday.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /holidays/1
  # DELETE /holidays/1.json
  def destroy
    @holiday.destroy
    respond_to do |format|
      format.html { redirect_to holidays_url, notice: 'Holiday request was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_holiday
      @holiday = Holiday.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def holiday_params
      params.require(:holiday).permit(:dateTo, :dateFrom, :Department, :Employee)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/holidays_helper.rb
module HolidaysHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/departments/_form.html.erb
<%= form_for(@department) do |f| %>
  <% if @department.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@department.errors.count, "error") %> prohibited this department from being saved:</h2>

      <ul>
      <% @department.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :position %><br>
    <%= f.text_field :position %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/departments/edit.html.erb
<h1>Editing department</h1>

<%= render 'form' %>

<%= link_to 'Show', @department %> |
<%= link_to 'Back', departments_path %>

app/views/departments/index.html.erb
<h1>Listing departments</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Position</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @departments.each do |department| %>
      <tr>
        <td><%= department.name %></td>
        <td><%= department.position %></td>
        <td><%= department.status %></td>
        <td><%= link_to 'Show', department %></td>
        <td><%= link_to 'Edit', edit_department_path(department) %></td>
        <td><%= link_to 'Destroy', department, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Department', new_department_path %>

app/views/departments/new.html.erb
<h1>New department</h1>

<%= render 'form' %>

<%= link_to 'Back', departments_path %>

app/views/departments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @department.name %>
</p>

<p>
  <strong>Position:</strong>
  <%= @department.position %>
</p>

<p>
  <strong>Status:</strong>
  <%= @department.status %>
</p>

<%= link_to 'Edit', edit_department_path(@department) %> |
<%= link_to 'Back', departments_path %>

app/views/holidays/_form.html.erb
<%= form_for(@holiday) do |f| %>
  <% if @holiday.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@holiday.errors.count, "error") %> prohibited this holiday from being saved:</h2>

      <ul>
      <% @holiday.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :dateTo %><br>
    <%= f.date_select :dateTo %>
  </div>
  <div class="field">
    <%= f.label :dateFrom %><br>
    <%= f.date_select :dateFrom %>
  </div>
  <div class="field">
    <%= f.label :Department %><br>
    <%= f.text_field :Department %>
  </div>
  <div class="field">
    <%= f.label :Employee %><br>
    <%= f.text_field :Employee %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/holidays/edit.html.erb
<h1>Editing holiday</h1>

<%= render 'form' %>

<%= link_to 'Show', @holiday %> |
<%= link_to 'Back', holidays_path %>

app/views/holidays/index.html.erb
<div class="row">
<h1>Listing holidays</h1>
<div class="pull-right range-query">
  
  <%= form_tag form_tag holidays_path, method: :get do %>
    <%= text_field_tag 'search[dateTo_from]', @search.dateTo_from %>
    <%= text_field_tag 'search[dateFrom_to]', @search.dateFrom_to %>
    <%= submit_tag 'search', class: 'btn_search-button' %>
  <% end %>  
  </div>
  </div>
<div class="media">
  <div class="media-body">
    <table class="table table-hover">
      <thead>
        <tr>
      <th>Dateto</th>
      <th>Datefrom</th>
      <th>Department</th>
      <th>Employee</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @holidays.each do |holiday| %>
      <tr>
        <td><%= holiday.dateTo %></td>
        <td><%= holiday.dateFrom %></td>
        <td><%= holiday.Department %></td>
        <td><%= holiday.Employee %></td>
        <td><%= link_to 'Show', holiday, class: 'btn btn-mini' %></td>
        <td><%= link_to 'Edit', edit_holiday_path(holiday), class: 'btn btn-mini btn-success' %></td>
        <td><%= link_to 'Destroy', holiday, method: :delete, class: 'btn btn-mini btn-danger', data: { confirm: 'Are you sure?' } %></td>
          </tr>
    <% end %>
  </tbody>
  </table>
  </div>
</div>

<br>

<%= link_to 'New Holiday', new_holiday_path %>

app/views/holidays/new.html.erb
<h1>New holiday</h1>

<%= render 'form' %>

<%= link_to 'Back', holidays_path %>

app/views/holidays/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Dateto:</strong>
  <%= @holiday.dateTo %>
</p>

<p>
  <strong>Datefrom:</strong>
  <%= @holiday.dateFrom %>
</p>

<p>
  <strong>Department:</strong>
  <%= @holiday.Department %>
</p>

<p>
  <strong>Employee:</strong>
  <%= @holiday.Employee %>
</p>

<%= link_to 'Edit', edit_holiday_path(@holiday) %> |
<%= link_to 'Back', holidays_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HR App</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <ul class="nav nav-tabs">
    <li><%= link_to "Home", root_path %></li>
    <li><%= link_to "About Us", welcome_about_path %></li>
    <li><%= link_to "Contact", welcome_contact_path %></li>
    <li><%= link_to "Holidays", holidays_path %></li>
    <li><%= link_to "Monday", root_path %></li>
    
      <% if current_user %>
      <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
    <% else %>
      <li><%= link_to "Sign Up", new_user_registration_path %></li>
      <li><%= link_to "Sign In", new_user_session_path %></li>
    <% end %>

  </ul>

  <% if flash[:notice] %>
    <div class="alert alert-success">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:notice] %>
    </div>
  <% elsif flash[:error] %>
    <div class="alert alert-error">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:error] %>
    </div>
  <% elsif flash[:alert] %>
    <div class="alert">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:alert] %>
    </div>
  <% end %>
  
  <%= yield %>
  
</div>

</body>
</html>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>

<p>Find me anywhere</p>

app/views/welcome/contact.html.erb
<h1>Welcome#contact</h1>
<p>Find me in app/views/welcome/contact.html.erb</p>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>